import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const aptos = localFont({
    src: "./Aptos.ttf", // Pastikan nama filenya sama persis ya, besar-kecil huruf ngaruh!
    variable: "--font-aptos",
    display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${aptos.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
